// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using readmypen.DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace readmypen.DataAccess.Entities
{
    public partial interface IAppDbContextProcedures
    {
        Task<int> UDP_Acce_tbUsers_InsertAsync(string usr_Username, string usr_Password, int? rol_Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UDP_Acce_tbUsers_LoginResult>> UDP_Acce_tbUsers_LoginAsync(string usr_Username, string usr_Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
