// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace readmypen.DataAccess.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbUsers = new HashSet<tbUsers>();
        }

        public int rol_Id { get; set; }
        public string rol_Description { get; set; }

        public virtual ICollection<tbUsers> tbUsers { get; set; }
    }
}