// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace readmypen.DataAccess.Entities
{
    public partial class tbUsers
    {
        public tbUsers()
        {
            tbPictures = new HashSet<tbPictures>();
        }

        public int usr_Id { get; set; }
        public string usr_Username { get; set; }
        public byte[] usr_Password { get; set; }
        public int rol_Id { get; set; }

        public virtual tbRoles rol { get; set; }
        public virtual ICollection<tbPictures> tbPictures { get; set; }
    }
}