// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace readmypen.DataAccess.Entities
{
    public partial class UDP_Acce_tbUsers_LoginResult
    {
        public string usr_Username { get; set; }
        public byte[] usr_Password { get; set; }
        public int rol_Id { get; set; }
    }
}
